#!/bin/sh

VERSION=0.8.3

cd /tmp
curl -L -o bitcoin.dmg http://sourceforge.net/projects/bitcoin/files/Bitcoin/bitcoin-$VERSION/bitcoin-$VERSION-macosx.dmg/download
hdiutil attach bitcoin.dmg
sudo rm -rf /Application/Bitcoin-Qt.app
sudo cp -r /Volumes/Bitcoin-Qt/Bitcoin-Qt.app /Applications/

hdiutil detach /Volumes/Bitcoin-Qt
rm bitcoin.dmg
