# Setting for the new UTF-8 terminal support in Lion
#export LC_CTYPE=en_US.UTF-8
#export LC_ALL=en_US.UTF-8
export LC_CTYPE=ru_RU.UTF-8
#export LC_ALL=ru_RU.UTF-8
export LC_COLLATE=C

export EDITOR=vim

export DMSERVER=20

#macbook
#0 – Legacy sleep mode. It will save everything to RAM upon sleeping but does not support “Safe Sleep”. Very fast sleep.
#1 – Legacy “Safe Sleep”. This is the “Safe Sleep”. Everything your laptop goes into sleep, it will save everything to harddisk. Slow on Sleep and Startup.
#3 – Default. As described above, when sleeping, contents are saved to RAM. When battery runs out, hibernate occurs.
#5 – Behaves as 1 but applicable only for modern Mac that uses “Secure virtual memory”.
#7 – Behaves as 3 but applicable only for modern Mac that uses “Secure virtual memory”
alias hibernateon="sudo pmset -a hibernatemode 5"
alias hibernateoff="sudo pmset -a hibernatemode 3"

#easy tether
alias tetheroff='sudo kextunload /System/Library/Extensions/EasyTetherUSBEthernet.kext'
alias tetheron='sudo kextload /System/Library/Extensions/EasyTetherUSBEthernet.kext'

#export PWS="$HOME/.safe/pws"
alias pw='pws'
alias pingt="mtr "
alias mysqld='mysql.server start'

alias macsleep="osascript -e 'tell application \"System Events\" to sleep'"
alias freehd="df -h / | awk 'END {print \$4}'"

alias memcacheddm='memcached -d -p 11233'

alias pyserv='python -m SimpleHTTPServer'


alias ll='ls -al'
alias l='ls -l'
#http://blog.willj.net/2011/05/31/setting-up-postgresql-for-ruby-on-rails-development-on-os-x/

# Brew
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH
# Postgresql
alias pgstart='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias pgstop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
alias pgtest='ps auxwww | grep postgres'
alias psqlp='psql -h localhost -U postgres '
###########

# Константы цветов
COLOR_YELLOW="\[\e[33;10m\]"
COLOR_RED="\[\e[31;10m\]"
COLOR_GREEN="\[\e[32;10m\]"
COLOR_BLUE="\[\e[34;10m\]"
COLOR_NONE="\[\e[0m\]"
COLOR_NONEP="\[\e[38;0m\]"

function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

#\h:\W \u\$
PS1="\h:\W\$(parse_git_branch)\$ "


alias sshx='export DISPLAY=:0.0 && open /Applications/Utilities/X11.app && ssh -X'
alias biggest='find ./ -type f -ls | sort -k 7 -r -n | head -10'

# ALIASES FOR FAST WORK WITH GIT
alias gs='git status '
alias ga='git add -A'
alias gap='git add -p'
alias gc='git commit -a'
alias gcm='git commit -m '
alias gca='git commit --amend -a '
alias gb='git branch '
alias gd='git diff '
alias go='git checkout '
alias gp='git push '
alias gpu='git pull '
alias gg='git add -A && git commit -a && git push'
alias gm='git merge --no-ff '
alias gl='git log -1 HEAD '
alias gignore='git rm -r --cached . && git add . && git commit -m ".gitignore is now working"'
alias glog='git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'


alias rsyncmove="rsync --partial --progress --append --rsh=ssh -r -h --remove-sent-files"
alias torssh='ssh -o ProxyCommand="nc -X 4 -x localhost:9050 %h %p"'

alias rvmu='rvm use $1@${PWD##*/} --rvmrc --create'

if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi
############################## EOF ############################


##
# Your previous /Users/nyaa/.bash_profile file was backed up as /Users/nyaa/.bash_profile.macports-saved_2012-01-10_at_19:07:28
##

# MacPorts Installer addition on 2012-01-10_at_19:07:28: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function

sssh(){
    # try to connect every 0.5 secs (modulo timeouts)
      while true; do command ssh "$@"; [ $? -ne 255 ] && break || sleep 0.5; done
    }
